import Head from 'next/head';
import About from '../components/About';
import Contact from '../components/Contact';
import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>JB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Header />
        <div className="snap-y overflow-y-scroll h-[100vh]  snap-mandatory flex flex-col">
          <section className="h-[100vh]  snap-start  flex flex-col items-end">
            <About />
          </section>
          <section className="h-[100vh]  snap-start  flex flex-col items-end"></section>
          <section className="h-[100vh] snap-start  flex flex-col items-end"></section>
          <section className="h-[100vh] snap-start flex flex-col items-end">
            <Contact />
          </section>
        </div>
      </main>
    </div>
  );
}
